name: CI
on: [push]
jobs:

  build:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
        go: ["1.16"]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make build

    - name: Test
      run: make test
